### ISSUE TITLE
Chart recalculate trigger is generated many times

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor-docker#5] opened 2020-06-22 16:40 UTC
When loading the page the chart are recalculated over 5 times that could slow down the system

![image](https://user-images.githubusercontent.com/1484241/85312922-caa44700-b4b7-11ea-81fd-3ef77bd56814.png)

**Comment by opatiny** [comment] 2020-06-23 06:53
The charts are generated many times because of the "link in" node, which is connected to all the charts input, to ensure that they refresh whenever a user clicks something. The problem is that when one connects to the UI, all the buttons are triggered and the charts are refreshed many times.

To solve this, we implemented a "gate" node, which blocks all messages when in closed state. The gate is closed by default and is opened when the someone connects to the GUI after a delay of 5 seconds.

![Screen Shot 2020-06-23 at 08 48 12](https://user-images.githubusercontent.com/17711389/85370175-9ae45600-b52e-11ea-9b2f-0655021eba20.png)

**Closed as completed** 2020-06-23 06:55 UTC
